### ISSUE TITLE
Implementation Details on SwinTrack-T-224

### ISSUE THREAD

**Issue by ElliottZhen** [Kou-99/ZoomTrack#2]
Hello, I have noticed that you have done experiments on SwinTrack-224 to verify the effectiveness of your module. 
Since it is of different sizes from OSTrack-256, I would like to ask whether some hyperparameters in the Implementation Details of Swintrack-224 are the same. Or you can make public the code of the data processing part in SwinTrack, because I want to learn from your excellent achievements. 
Thank you very much, I wish you a smooth scientific research, good health, happy winter solstice!

**Comment by Kou-99** [comment]
The hyper-parameter for Swintrack-224 and OSTrack-256 are the same except that the search factor for Swintrack-224 is 4.5 and the search factor for OSTrack-256 is 5. We use a smaller search factor to compensate for the smaller input size. The logic of data processing is the same as the OSTrack version.
