### ISSUE TITLE
Problem of label mapping when calculating loss/关于计算损失时标签映射的问题

### ISSUE THREAD

**Issue by ElliottZhen** [Kou-99/ZoomTrack#3]
Hello, I want to apply your method to my tracker. In the part of loss calculation, I have encountered a problem. In my regression loss, both the predicted score graph and boundary box are used in the calculation of loss, just like SwinTrack. You mentioned in your paper that when you implement your method to a universal tracker, you need to reverse map the prediction boundary box to calculate the regression loss, so similarly, I think in my tracker, the score plot needs to be reversed mapped.

I have two questions for you:

1. Can I map the ground truth bounding box from I to I 'through grid g when calculating regression loss? This way I don't have to reverse map the predicted score plot and borders when calculating regression losses.

2.SwinTrack should also use the classification graph and take the fractional graph as the weight when calculating regression loss. May I ask that the label mapping strategy you used in the calculation of regression loss during the ablation experiment on SwinTrack is also Reverse box mapping. So how to deal with classification graph weights?

I'm sorry to bother you, because the hardware conditions are limited, so I can only ask you for some experience, thank you very much!

 

你好，我想把你的方法应用到我的跟踪器，在计算损失部分，我遇到了一个问题，我的回归损失里边，计算损失时，预测的分数图和边界框都用到了，像SwinTrack那样。而您在论文提到了，将您的方法实施到通用跟踪器时，计算回归损失，需要把预测边界框反向映射，那么同样的，我认为在我的跟踪器中，分数图也需要反向映射。
我有两个问题想请教一下你：
1.我是否可以在计算回归损失时，通过网格g将ground truth bounding box从I映射到I’；这样我在计算回归损失时，预测的分数图和边框就不用反向映射。
2.SwinTrack在计算回归损失时，应该也用到了分类图，把分数图作为权重，请问你在SwinTrack上做消融实验时，计算回归损失这部分，用到的标签映射策略也是Reverse box mapping。那么分类图权重如何处理呢？
很抱歉打扰您，因为硬件条件有限，所以只能向您请教一些经验，非常感谢！

@Kou-99

**Comment by Kou-99** [comment]
1. It is possible to map the bounding box from I to I'. Function warp_boxes in /lib/train/data/grid_generator.py is the implementation.
2. The classification map for SwinTrack is generated by the ground truth bounding box on I', which is generated from the ground truth bounding box on I using warp_boxes.
