### ISSUE TITLE
How to get the FPS?

### ISSUE THREAD

**Issue by ShaohuaDong2021** [Kou-99/ZoomTrack#5]
Hello, do you know how to get the FPS? Thanks a lot!

**Comment by Kou-99** [comment]
You can use tracking/profile_model.py to get macs and fps

**Comment by ShaohuaDong2021** [comment]
Thanks. But I got same FPS for OSTrack and Zoomtrack. As shown in your paper, the zoomtrack speed should slower.
Maybe I miss something, can you give me more information?

**Comment by Kou-99** [comment]
The FPS mentioned in the paper is calculated by combining the model latency (obtained from profile_model.py) with the resize latency. Upon reviewing the repository, I've realized that I forget to include the code for evaluating resize latency. Unfortunately, I'm currently in the midst of a project, so I don't have time to transfer this code to the repository. If you're interested, please leave your email, and I'll send you the original code. Please note that some modifications may be necessary to ensure compatibility with this repository. My apologies for any inconvenience caused!
