### ISSUE TITLE
There is an error in the code

### ISSUE THREAD

**Issue by wangyujie615** [Kou-99/ZoomTrack#6]
File "/data2/wangyujie/ZoomTrack/lib/train/../../lib/train/actors/hivitr_zoom_actor.py", line 84, in compute_losses
    pred_boxes_vec = unwarp_bboxes_batch(box_cxcywh_to_xyxy(pred_dict['pred_boxes']), gt_dict['search_grids'][0]).view(-1, 4)
KeyError: 'search_grids'

**Comment by Kou-99** [comment]
1. check if you use QpProcessing (lib.train.data.processing.py) as data processing
2. check if arg use_grid is correctly configured when initializing QpProcessing 
An example can be found in /lib/train/train_settings/ostrack.py line 73~95
